### PR TITLE
only unset superfluous env vars on `env_write`

### PR DESCRIPTION
**Pull request by andre-merzky**
@AymenFJA : this fix should resolve https://github.com/radical-cybertools/radical.pilot/issues/2489 - please give it a try.  Thanks!

### CODE REVIEW

**Comment by AymenFJA** [comment]
Hello @andre-merzky, unfortunately, this did not fix the problem:

```
Traceback (most recent call last):
  File "./raptor_master.py", line 9, in <module>
    import radical.utils as ru
ImportError: No module named 'radical'
```

```
(raptor) (base) aymen@js-17-213:~/RADICAL/parsl_raptor/radical.pilot/examples/misc$ radical-stack

  python               : /home/aymen/ve/raptor/bin/python3
  pythonpath           :
  version              : 3.7.6
  virtualenv           : /home/aymen/ve/raptor

  radical.gtod         : 1.6.7
  radical.pilot        : 1.11.2-v1.11.2-78-gc088983@feature-parsl_raptor_executor
  radical.saga         : 1.11.1
  radical.utils        : 1.11.0-v1.11.0-1-g7c9997f@hotfix-env_write
```

FYI, due to some bootstrapping problems because of this file `radical.utils/bin/radical-utils-env.sh` (I will open a new ticket regarding that), I had to use the following settings under the `resource_local.json`: 

```
 "rp_version"                  : "installed",
 "virtenv_mode"                : "use",
 "python_dist"                 : "virtual_env",
 "virtenv"                     : "/home/aymen/ve/raptor/",
```

The new pilot sandbox is attached here. 

[pilot.0000.zip](https://github.com/radical-cybertools/radical.utils/files/7979898/pilot.0000.zip)

**Comment by andre-merzky** [comment]
The file`examiples/misc/raptor.py` contains an `prepare_env` call in line 87ff - what did you use there?  (the committed code points to a dir which won't exist on your machine)

**Comment by AymenFJA** [comment]
> The file`examiples/misc/raptor.py` contains an `prepare_env` call in line 87ff - what did you use there? (the committed code points to a dir which won't exist on your machine)

```python
pilot.prepare_env(env_name='ve_raptor',
                  env_spec={'type'   : 'virtualenv',
                            'version': '3.7.6',
                            'path'   : '/home/aymen/radical.pilot.sandbox/ve_raptor',
                            'setup'  : [
                               #'pip install git+https://github.com/radical-cybertools/radical.pilot.git@feature/raptor_workers',
                               #'pip install git+https://github.com/radical-cybertools/radical.utils.git@feature/faster_zmq',
                            ]})
```

**Comment by andre-merzky** [comment]
Ah - then the venv gets created, but nothing is installed there...  You may want to enable the pip commands to get those module versions deployed, or install your stack manually there...

**Comment by andre-merzky** [comment]
@AymenFJA : can you please check if this is still a problem?  I have gotten a bit confused by the different strands on that set of problems...

**Review by AymenFJA — APPROVED** [review]
This problem is resolved, as I cannot see it anymore.

**Pull request merged**
