### PR TITLE
fix int and float parsing during env expansion

### PR DESCRIPTION
**Pull request by andre-merzky**
this fixes https://github.com/radical-cybertools/radical.saga/issues/739

### CODE REVIEW

**Comment by iparask** [comment]
@andre-merzky, this is a python2 branch. I cannot install it to a python3 env.

**Comment by andre-merzky** [comment]
Ah bugger - let me sync (it should merge cleanly)

**Comment by andre-merzky** [comment]
This is py3 based now.

**Comment by iparask** [comment]
I think the target branch should also be changed! :)

**Comment by andre-merzky** [comment]
> I think the target branch should also be changed! :)

It is already :-)  Probably crossed notifications...

**Comment by iparask** [comment]
This works

**Comment by andre-merzky** [comment]
Thanks!

**Pull request merged**
