### PR TITLE
Add configurable csv field size limit

### PR DESCRIPTION
**Pull request by mturilli**
This should enable profiling of very large sessions.

### CODE REVIEW

**Comment by mturilli** [comment]
About the failing tests, can we make `'_foo' : str,` in `tests/unittests/test_description.py:_schema` `'foo' : str,`, seeing that `_schema` is already private?

**Comment by mturilli** [comment]
About the failing test, in  I see:
```
try:
    # make pylint happy - this is optional code
    from Xlib import X, display, Xutil
except:
    raise RuntimeError('need Xlib module to work')
```
I am not sure how this should make pylint happy and it doesn't. Should we use `pip install python3_xlib` instead and, seeing that we want to use Xlib (I don't, BTW) add python3_xlib as a required module?

**Comment by andre-merzky** [comment]
Xlib: well, it used to pacify pylint :-P  xlib is not always available nor installable, I'm not sure if we want to make the tests depend on it.  Not sure how to handle that best.  Maybe installing it in travis is worth a try, we'll see if it's installable there...

**Comment by andre-merzky** [comment]
`_foo`: accessing `_foo` this way *is* the test.  I don't know why the `noqa` tag is ignored, and gave up trying to understand :-/

**Pull request merged**
