### PR TITLE
updated CI

### PR DESCRIPTION
**Pull request by mtitov**

### CODE REVIEW

**Comment by andre-merzky** [comment]
What is the plan for this PR? :-)

**Comment by mtitov** [comment]
@andre-merzky should we re-review this PR (just that #404 stuck with codecov worries me), I'm ok if you'll take over this PR

**Comment by andre-merzky** [comment]
> @andre-merzky should we re-review this PR (just that #404 stuck with codecov worries me), I'm ok if you'll take over this PR

Yep, I am game to get this one done.  The Codecov timeouts are really annoying, they pop up more and more frequently nowadays.  I added a timeout to #404 now, but well, that causes the tests to fail which is not much better ...  Let's discuss codecov on the next call...

**Review by andre-merzky — APPROVED** [review]
This looks good to me - thanks!

**Pull request merged**
