### PR TITLE
Feature/demo

### PR DESCRIPTION
**Pull request by andre-merzky**
Lots of formatting tweaks, adding an idle mode for reporter, make LogReporter respect log level settings, simplify log reporter use (`logger.demo('info', msg) --> logger.report.info(msg)`)

### CODE REVIEW

**Comment by andre-merzky** [comment]
I left the `logger.demo('info', msg)` syntax in place for backward compatibility -- but since this is young code, I would also not mind removing it.  Its is not used at the moment...

**Comment by marksantcroos** [comment]
> I would also not mind removing it. Its is not used at the moment...

Im all for unified interfaces.

**Comment by andre-merzky** [comment]
I'll do that then.  brb :)

**Comment by andre-merzky** [comment]
I would not mind if that would be merged soon, for testing documentation examples etc.

**Comment by marksantcroos** [comment]
I believe we didnt do this earlier because it broke RP devel IIRC.

**Comment by marksantcroos** [comment]
Just verified, that is still the case:
```
2015-10-13 09:58:45,679: radical.pilot       : MainProcess                     : MainThread     : ERROR   : session create failed
Traceback (most recent call last):
  File "/Users/mark/.virtualenv/rp/lib/python2.7/site-packages/radical/pilot/session.py", line 137, in __init__
    logger.demo('info', 'create session %s' % self._uid)
AttributeError: 'Logger' object has no attribute 'demo'
```

**Comment by andre-merzky** [comment]
Ah, right - but then again, that might be a decent point to start merging RP doc-things toward 0.37 by now.  Let me get those PRs in place then, if you don't mind...

**Comment by marksantcroos** [comment]
sff-thanks-colour-tight

**Pull request merged**
