### PR TITLE
silence queue logs

### PR DESCRIPTION
**Pull request by andre-merzky**
This fixes radical-cybertools/radical.pilot/issues/2085

### CODE REVIEW

**Comment by mturilli** [comment]
Note that one of the test fails with:
```
src/radical/utils/zmq/pubsub.py

  32  4   W0235   Useless super delegation in method '__init__' (useless-super-delegation)
```
Is that the case?

**Comment by andre-merzky** [comment]
> Note that one of the test fails with:
> 
> ```
> src/radical/utils/zmq/pubsub.py
> 
>   32  4   W0235   Useless super delegation in method '__init__' (useless-super-delegation)
> ```
> 
> Is that the case?

Kind-of yes, as the default inheritance will kick in anyway.  But the explicit delegation makes this, well, explicit, so it's there on purpose.  I disable the warning.

**Comment by andre-merzky** [comment]
> Could you merge this also in hotfix/frontera so that I can measure how relevant the reduction in log size is?

@mturilli : since the fix is in RU, the `hotfix/frontera` RP branch should benefit immediately.

**Comment by andre-merzky** [comment]
> Could you merge this also in hotfix/frontera so that I can measure how relevant the reduction in log size is?

@mturilli : since the fix is in RU, the `hotfix/frontera` RP branch should benefit immediately.

**Pull request merged**
